### ISSUE TITLE
not an issue - but fyi - ANTLR-Swift-Target / Antlr-Swift-Runtime

### ISSUE THREAD

**Issue by johndpope** [yanagiba/swift-ast#13]
The ANTLR-Swift-Target was merged into antlr https://github.com/antlr/antlr4 official repo. 

https://github.com/janyou/ANTLR-Swift-Target/pull/10

https://github.com/johndpope/Antlr-Swift-Runtime

I built the java / golang / proto parser here
https://github.com/johndpope/Antlr-Swift-Runtime/tree/master/Test/Test

other languages here
https://github.com/johndpope/ANTLR-Swift-Target/tree/master/gen/grammars-v4

I'm interested to do machine learning language translation DRAGGNN with tensorflow by training on generated languages from one -> then translating the AST in SWIFT. eg. give me a golang class -> spit out the corresponding swift file. 

let me know if your interested
made some progress here - https://github.com/nubbel/swift-tensorflow/

**Comment by wwe-johndpope** [comment]
Been looking through codebase and unit tests and code looks nice.

This class is currently spitting out basic lever /parser /token classes in swift for any given gramma file.
It's in c++ but renders down to swift. I guess you haven't seen this library before / but can you see any pros with this library vs the official one?

https://github.com/antlr/antlr4/blob/4.7/tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg

I wondered if one day this code generation could be driven by a swift template using stencilkit instead of c++ and java.

**Comment by wwe-johndpope** [comment]
Said another way, given a swift gramma file could you spit out this library?
https://github.com/antlr/grammars-v4/tree/master/swift3

**Comment by ryuichis** [comment]
Hey @johndpope @wwe-johndpope, thanks for sharing. I actually briefly looked into Antlr before I started working on the very first prototype of this project. At that time, the Apple Swift compiler was not open sourced, and Antlr was one of my few options if I decide to use a parser generator like it. I also looked into another one (even forget the name right now), and it is a C/C++ based. I spent some time on it, and also decided to not move forward with that direction.

The main purpose of writing this library for the time-being is for swift-lint and swift-format projects, so the AST at the moment is really biased towards that goal. But I do think long term, it could be a solid infrastructure for building other developer tools, like codegens.

If I understand you correctly, I believe once swift-format project is built, you can also leverage the AST defined in this project, and let swift-format outputs a Swift file for you. Basically, once you have the AST from your golang class, write a factory and map the Golang AST to this AST, and then just print out the Swift file. The `-print-ast` currently should also work for the majority of cases, but I would rather have a better separation of logic, and let `swift-format` handles that piece. Keep tuned and please bare with me.

If you want to discuss further, we can take the conversation to email: ryuichi@ryuichisaito.com
