### ISSUE TITLE
Semicolons not handled as expected

### ISSUE THREAD

**Issue by keeptyping** [yanagiba/swift-ast#61]
### Issue Summary
Semicolons not handled as expected.

### Environment
- OS Info: macOS Version 10.13.1 (Build 17B48)
- Yanagiba/swift-ast version: 0.4.1

### Reproduction Steps
Every _const_decl/var_decl_ which ends with a semicolon is treated as an error. 

<details>
<summary>Sample code</summary>

```

struct SemicolonIssue {
    
    private let issue = "";
    
}

```

Command to run `swift-ast` with the code above:
`swift-ast SemicolonIssue.swift`

</details>

### Expected Result
A successfully parsed TopLevelDeclaration.

### Actual Behavior
The parser failed with a badDeclaration error.

```
SemicolonIssue.swift:13:25 fatal: badDeclaration
```

**Comment by petermichaux** [comment]
I'm using SwiftKotlin (https://github.com/angelolloqui/SwiftKotlin) and unfortunately it does not accept semicolons. I think it because swift-ast does not accept semicolons. I hope swift-ast can be adjusted to accept semicolons.
