### ISSUE TITLE
Parser crashes when using value matching in catch clause

### ISSUE THREAD

**Issue by TheDutchDevil** [yanagiba/swift-ast#69]
### 🚨New Issue Checklist🚨

- [X] Updated swift-ast to the latest version
- [X] I have read the [Code of Conduct](http://contributor-covenant.org/version/1/4/)
- [X] I am aware that the `swift-ast -github-issue /path/to/file.swift` might help me generate this file

### Issue Summary
The file attached to this issue can be successfully built and executed using `swiftc` with no additional parameters.  I'm working on a project where we analyze the Error Handling behavior of open source Swift projects, therefore we need a Swift parser that can detect all kinds of usages of Swift error handling, including value matching in catch clauses. 

### Environment
- OS Info: Linux Subsystem for Windows 10
- Yanagiba/swift-ast version: 0.4.1

### Reproduction Steps
Parse the included file using `swift-ast -dump-ast <file>` and observe that it fails to parse the value matching in the catch clause. 

<details>
<summary>Sample code</summary>

```
enum VendingMachineError: Error {
        case insufficientFunds(coinsNeeded: Int)
}

func throwsSomething() throws -> String {

        return "This doesn't matter"

}


do {

        try throwsSomething()

}
catch VendingMachineError.insufficientFunds(3) {
        print("3 coins missing")
}
catch VendingMachineError.insufficientFunds(let coinsNeeded) {
        print("Not 3 coins missing")
}
catch {
        print("No coins missing")
}

```

Command to run `swift-ast` with the code above:
`swift-ast /home/nathan/value_ex.swift`

</details>

### Expected Result
A valid ast dump for the test file, it appears that swift-ast does not correctly parse the type instantiation for the value matching. 

### Actual Behavior

```
/home/nathan/value_ex.swift:17:45 fatal: expectedPattern
```

**Comment by ryuichis** [comment]
@TheDutchDevil thanks for letting me know. I can reproduce the issue locally. I will try my best to work on a fix between Christmas and New Year, otherwise, will be early Jan.

**Comment by TheDutchDevil** [comment]
@ryuichis Thanks a lot for your quick response and work on the parser!

**Comment by TheDutchDevil** [comment]
Thanks a lot for the quick fix!

**Comment by ryuichis** [comment]
@TheDutchDevil no problem, thanks for informing me with the issue. Happy new year!
