### ISSUE TITLE
Parsing of pattern matching on type for catch clause. 

### ISSUE THREAD

**Issue by TheDutchDevil** [yanagiba/swift-ast#75]
### 🚨New Issue Checklist🚨

- [x] Updated swift-ast to the latest version
- [x] I have read the [Code of Conduct](http://contributor-covenant.org/version/1/4/)
- [x] I am aware that the `swift-ast -github-issue /path/to/file.swift` might help me generate this file

### Issue Summary
The parsing of type matching in the catch clause pattern fails, while swift itself can compile the file. 

### Environment
- OS Info: Linux subsystem for Windows 10
- Yanagiba/swift-ast version: 0.4.1

### Reproduction Steps
Parse the included code example.

<details>
<summary>Sample code</summary>

```
enum someErr: Error {
        case woops
}

func badstuffhappens() throws -> String {
        throw someErr.woops
}

try? badstuffhappens()

try! badstuffhappens()

do {
        try badstuffhappens()
} catch someErr.woops {

}
catch is someErr {

}


```

Command to run `swift-ast` with the code above:
`swift-ast /home/nathan/hw.swift`

</details>

### Actual Behavior
Parsing fails because the `is` keyword is not expected. 

```
/home/nathan/hw.swift:26:7 fatal: expectedPattern
```

**Comment by ryuichis** [comment]
@TheDutchDevil did you pull the latest changes? I can't reproduce the issue with your sample code. Please check out this change set b09a17c66fcb1f84947530dae70087492597b7a9 and help verify if I misunderstood anything.

**Comment by TheDutchDevil** [comment]
My bad, I had an old version of swift-ast in my path which threw the error. Apologies for the confusion.
