### ISSUE TITLE
ExpectedPattern in field declaration of struct

### ISSUE THREAD

**Issue by TheDutchDevil** [yanagiba/swift-ast#81]
### Issue Summary
The variable defined as optional fails when parsed because of a failure to detect an expected pattern. However, as I don't see anything wrong with this code. 

Side-note, the Swift 4 compiler parses this file (`swiftc -parse <FILE>`), I updated swift-ast to the latest version, and this file is not my own. 

### Environment
- OS Info: Linux for Windows 10
- Yanagiba/swift-ast version: 0.4.1

<details>
<summary>Sample code</summary>

```
/// Various types of fields
/// that can be used in a Schema.
public struct Field {
    public let name: String
    public let type: DataType
    public let optional: Bool
    public let unique: Bool
    public let `default`: Node?
    public let primaryKey: Bool

    public enum DataType {
        case id(type: IdentifierType)
        case int
        case string(length: Int?)
        case double
        case bool
        case bytes
        case date
        case custom(type: String)
    }

    public init(
        name: String,
        type: DataType,
        optional: Bool = false,
        unique: Bool = false,
        default: Node? = nil,
        primaryKey: Bool = false
    ) {
        self.name = name
        self.type = type
        self.optional = optional
        self.unique = unique
        self.default = `default`
        self.primaryKey = primaryKey
    }

    public init(
        name: String,
        type: DataType,
        optional: Bool = false,
        unique: Bool = false,
        default: NodeRepresentable? = nil,
        primaryKey: Bool = false
    ) {
        let node: Node?

        if let d = `default` {
            node = try? d.makeNode(in: rowContext)
        } else {
            node = nil
        }

        self.init(
            name: name,
            type: type,
            optional: optional,
            unique: unique,
            default: node,
            primaryKey: primaryKey
        )
    }
}

extension Field: Equatable {
    public static func ==(lhs: Field, rhs: Field) -> Bool {
        return lhs.name == rhs.name
            && lhs.type == rhs.type
            && lhs.optional == rhs.optional
            && lhs.unique == rhs.unique
            && lhs.default == rhs.default
            && lhs.primaryKey == rhs.primaryKey
    }
}

extension Field.DataType: Equatable {
    public static func ==(lhs: Field.DataType, rhs: Field.DataType) -> Bool {
        switch (lhs, rhs) {
        case (.id(let a), .id(let b)):
            return a == b
        case (.int, .int),
             (.string, .string),
             (.double, .double),
             (.bool, .bool),
             (.bytes, .bytes),
             (.date, .date):
            return true
        case (.custom(let a), .custom(let b)):
            return a == b
        default:
            return false
        }
    }
}

extension IdentifierType: Equatable {
    public static func ==(lhs: IdentifierType, rhs: IdentifierType) -> Bool {
        switch (lhs, rhs) {
        case (.int, .int),
             (.uuid, .uuid):
            return true
        case (.custom(let a), .custom(let b)):
            return a == b
        default:
            return false
        }
    }
}

```

Command to run `swift-ast` with the code above:
`swift-ast /mnt/d/swift_repos/72896077/fluent/Sources/Fluent/Schema/Field.swift`

</details>

### Actual Behavior
Parser fails on line 7:16

```
/mnt/d/swift_repos/72896077/fluent/Sources/Fluent/Schema/Field.swift:7:16 fatal: expectedPattern
```

**Comment by TheDutchDevil** [comment]
I looked into the problem some more and it turns out that according to the apple docs `optional` is a conditional keyword, and is only considered to be a keyword in specific instances. Probably if `optional` occurs as part of a protocol definition. See: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/LexicalStructure.html 

Furthermore, it appears that the `optional` keyword in Swift 4 can only be use together with `@objc`: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Declarations.html#//apple_ref/doc/uid/TP40014097-CH34-ID351 (Search for optional on the page) and: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Protocols.html#//apple_ref/doc/uid/TP40014097-CH25-ID284

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
