### ISSUE TITLE
Unable to build on Mac OSX xcode 7.3.1(7D1014)

### ISSUE THREAD

**Issue by kaning** [yanagiba/swift-ast#9]
I get the following:

`unable to invoke subcommand: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build (No such file or directory)`

**Comment by ryuichis** [comment]
Check out https://github.com/yanagiba/swift-ast/blob/master/.swift-version, you need that particular swift-3 snapshot version installed.
