### ISSUE TITLE
Can convert Swift AST to Swift source code?

### ISSUE THREAD

**Issue by LuckyRoc** [yanagiba/swift-ast#94]
### 🚨New Issue Checklist🚨

- [x] Updated swift-ast to the latest version
- [x] I am aware that the `swift-ast -github-issue /path/to/file.swift` might help me generate this file

### Issue Summary
[Insert a brief but thorough description of the issue]

### Environment
- OS Info: [Please insert the operating system name and version]
- Yanagiba/swift-ast version: [Please insert the swift-ast version]

### Reproduction Steps
[Detailed steps to reproduce the issue.]

<details>
<summary>Sample code</summary>

```
[Insert sample source code here]
```

Command to run `swift-ast` with the code above:
`swift-ast sample.swift`
</details>

### Expected Result
What do you expect to happen as a result of the reproduction steps?

### Actual Behavior
What currently happens as a result of the reproduction steps?

```
[
  Insert the current outputs and
  maybe other information that
  could help us understand the issue better
]
```

### Even Better
Is your project open sourced? If yes, can you point us to your repository?
If not, is it possible to make a small project that fails the Travis CI?
If not, can you create a gist with your sample code for us?

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
